### PR TITLE
Added various tool cart improvements

### LINKED ISSUE #169: Add live size count to tool cart
When there are tools in the cart, the title of the wdiget should read something like "Tool Cart (3 tools)". Nothing additional should be shown if the cart is empty. This count should update live as tools are scanned.

### LINKED ISSUE #171: Tool cart should have a Remove All button
Not sure where this would fit best in the widget.

Also can we change the duplicate tool notice color to orange (warning) to differentiate it from the error message (which is red)?

### PR DESCRIPTION
**Pull request by purelogiq**
Fixes #169 (Live count size in title bar)
Fixes #171 (Remove all button) besides color of duplicate warning. Changing color of duplicate tool is doable but will take more time (have to refactor boolean to something with 3 states)

### CODE REVIEW

**Comment by pkoenig10** [comment]
2 things:

1) You need to reload the page the see the Remove All button.  Just remove the condition check and it will be fine (the table doesn't show if there aren't tools in the cart anyways).
2) Is there a reason we aren't using the <table>, <th>, <tr> tags? All other sidebars use this so we should too to be consistent.  I tried changing but sometimes tools wouldn't add to the cart. Not sure why. (On a related note, make sure to update the column widths in both the header and items, they are different as of this commit).

**Comment by purelogiq** [comment]
Oh yeah, I'm dumb. Forgot to add the javascript to show the remove button but yeah just removing the condition should work.

The table tags had the really wonky display when in use with the scrollbar. They will not work as you normally would hope. Unless you really want to use table tags I can't recommend them. 

Also while the header and body div column widths are different that doesn't impact the display of the cart. The remove button is too big to be just a 3 width column. Why not leave the columns as is?

**Comment by pkoenig10** [comment]
Okay makes sense.  I'll just remove the condition and merge.

**Comment by purelogiq** [comment]
I will change the color of the duplicate warning later tonight.

**Comment by pkoenig10** [comment]
Will that be a separate PR or in this one? If its separate, I'll merge this one.

**Comment by purelogiq** [comment]
Yup separate. Probably a "Misc fixes PR"

**Pull request merged**
