### PR TITLE
Added authorization checks - Home Controller & fixed Event okay/un-okay button

### PR DESCRIPTION
**Pull request by eleanorwilson**
Added checks so that if you are not logged in you can't access the /downtime (fixing bug #189) , /hardhats, or /charges_overview.

### CODE REVIEW

**Comment by eleanorwilson** [comment]
CI checks failing cause of the shift test (server issue, always 7 hours time difference) - reoccurring issue in all pull requests that we need to fix -- but not failing from the actual code that's being submitted

**Comment by pkoenig10** [comment]
Can you open an issue for this?

**Comment by eleanorwilson** [comment]
@pkoenig10  yeah will do!

**Comment by eleanorwilson** [comment]
Changed HTTP method with the event okay/unokay so that it now matches the HTTP method that was in the routes file so that it now works (resolves issue #199)

**Comment by blinblinblin** [comment]
This looks good to me. @pkoenig10  do you want to give it a look? Rumby fixed #189 and #199

**Comment by pkoenig10** [comment]
@blinblinblin yeah I'll take a look later tonight!

**Comment by pkoenig10** [comment]
LGTM. Would it be too much work to write a couple small tests for the authorization stuff? Authorization is really really important and we've had issues in the past with unauthorized access so we really should try to have good regression tests for auth stuff.

**Comment by blinblinblin** [comment]
It wasn't part of our plan to include tests on authorization but we can definitely add it to our agenda. It might be a good idea to come back later and visit this in details as we are meeting our first deadline tomorrow. Is this okay by you? @pkoenig10

**Comment by pkoenig10** [comment]
Yupp makes sense. It's definitely a lot of work. I'm mostly commenting just to give some extra context and point out things to keep on your radar you may not be aware of.

Remember to close out those issues when this merges (either in your working branch or whenever you merge to master)

**Pull request merged**
