### PR TITLE
New features branch

### PR DESCRIPTION
**Pull request by sclark**
This branch includes a number of new features, could you merge these into your working branch so that we can deploy and test all of these changes?

Thanks!

### CODE REVIEW

**Comment by sclark** [comment]
Oops, there is one feature I forgot! Can you wait to merge this PR until I merge PR #251 into new-features?

**Comment by sclark** [comment]
Are we still on track to finish this merge tonight?

**Comment by blinblinblin** [comment]
@sclark I'm looking at your PR right now. But I'm getting an error from home_controller when I try to login as a participant. Does this happen on your machine as well?

**Comment by blinblinblin** [comment]
I ran down the list of features and made sure that they function as accordingly. We ran into small bugs such as views but Stephen has fixed them all. Going to squash and merge this PR into the goat branch for deployment

**Pull request merged**
