### PR TITLE
Quick fixes for reports feature

### PR DESCRIPTION
**Pull request by purelogiq**
- Fixed bug with reporting tools that have been checked out.
- Sorted booth chair report by organization since organizations can have multiple booth chairs. (If you download the CSV you can use Excel to resort it as usual).

### CODE REVIEW

**Comment by pkoenig10** [comment]
@purelogiq Could you also add phone numbers and phone carriers to the reports that export members? I realized yesterday that was something we need.

**Comment by purelogiq** [comment]
Sure

**Comment by purelogiq** [comment]
Fixed. Also added a helpful reminder to restart server to test changes to reports for future teams (due to the way they dynamically get loaded).

**Comment by pkoenig10** [comment]
Is there a specific reason you changed all the reports to use SQL queries instead of ActiveRecord query methods? I prefer the ActiveRecord methods because they are more readable and maintainable.  Even if it does come with the overhead of having to define the column format names.

**Comment by purelogiq** [comment]
As far as using "AS" in the select rather than the format_header goes, format_header acts buggy when you have non-standard column names so AS was the only guarrentted way to get it to work.

Everything else is 'technically' impossible using activerecord (or at least I don't know how to do it). The `.select` statements are necessary because dossier's `display_column?` helper function only works on the html pages and the csv will select everything. 

The convoluted sub-selects (like the `CASE WHEN` and `phone_carrier`) are necessary because it is not possible to do it in a way with activerecord that works with dossier (since dossier needs 1 entire table returned by 1 statement). For example getting the phone_carrier, a `joins(participant: :phone_carrier)` doesn't work because that will filter out people who haven't set their phone carrier (and to use a left join you have to manually use sql anyway so I just did a sub-select).

**Comment by pkoenig10** [comment]
Okay sounds good.  I was doing some testing and noticed that the charges report doesn't pull any charges regardless of the parameters.  Maybe there is small bug in the query somewhere.

**Comment by purelogiq** [comment]
@pkoenig10 I just tried this on my end and it works fine. Did you create a charge or store purchase for an org? If so did you approve it? If you want to see the unapproved ones you have to check the 'pending charges' checkbox.

**Pull request merged**
