### PR TITLE
Allow store prices to be fractional

### PR DESCRIPTION
**Pull request by RONNCC**

### CODE REVIEW

**Comment by RONNCC** [comment]
#168

**Comment by purelogiq** [comment]
Going to look at this later. Also @RONNCC since Patrick is still deploying changes to production did you test how this will affect the existing database? A migration might be needed.

**Comment by pkoenig10** [comment]
I don't need to deploy to production anymore, so that shouldn't be an issue. I'm going to wait to deploy these batch of changes until after the semester.

**Comment by purelogiq** [comment]
Ok will take a quick look soon.

**Comment by purelogiq** [comment]
Yeah I would just say make a new migration for this as well.

**Comment by pkoenig10** [comment]
Closing because the semester project is over.

**Pull request closed without merging**
