### PR TITLE
Update gems rebased

### PR DESCRIPTION
**Pull request by minigeek**
Let's try this again, won't merge this time.

### CODE REVIEW

**Comment by minigeek** [comment]
Why does Coveralls think the coverage on Master is 16%?

**Comment by pkoenig10** [comment]
Its from 6a1135ae3334763ae1404412d8691c0a4901f6d1.  I added a staging environment and it looks like Coveralls went form checking 23 files to checking 69.  I'm pretty sure I didn't do anything that would have screwed that up.  Maybe you can take a look?

**Comment by minigeek** [comment]
The 16% actually looks legit, looks like it's finally seeing controllers. Not sure what changed, but it's probably a good thing.

**Comment by arakla** [comment]
Maybe because the gems were updated? Or they upgraded coveralls?

**Comment by minigeek** [comment]
But he didn't update anything as part of the commit that actually changed the coverage.

**Comment by minigeek** [comment]
But he didn't update anything as part of the commit that actually changed the coverage.

**Pull request merged**
