### PR TITLE
Reorganized top level navigation and separated sidebar into partials

### PR DESCRIPTION
**Pull request by pkoenig10**
- Slightly reorganized the nav bar menus to be more intuitive.  Added downtime and queue links to the nav bar.  Separated links into Other Links (general links) and SCC Links (SCC-specific features). Moved the sign waiver link to the right-side user dropdown.

- Slightly reorganized the quick links page (home page).  Changed some of the buttons and added a button to sign a waiver if a user is logged in who has not signed the waiver

- Moved all sidebar widgets into partials.

- Rearranged some of the sidebar widgets, made the tool cart collapsible, and change the default state (collapsed or not) for some widgets.

- Removed the option to mark an event as completed in the form for a new event.

### CODE REVIEW

**Comment by pkoenig10** [comment]
@purelogiq if you could look this over and merge it sometime today that would be great. It looks like a lot of changes only because I moved large chunks of code to separate files.

**Comment by purelogiq** [comment]
@pkoenig10 Testing it now with each user type

**Comment by purelogiq** [comment]
Are participants allowed to see the store? Right now they can't.

**Comment by purelogiq** [comment]
Is there a reason why you made shifts that aren't checked in green? It was red before.

**Comment by purelogiq** [comment]
@pkoenig10 Also I'm fixing some things so please don't push too much (so there are no conflicts)

**Comment by pkoenig10** [comment]
Sorry, just let me know when you're finished reviewing and push any changes you make.

**Comment by purelogiq** [comment]
@pkoenig10 Also you gave booth chairs the ability to update store items, is this correct?

**Comment by pkoenig10** [comment]
No, my bad, that was supposed to be under SCC members.

**Comment by pkoenig10** [comment]
I gave that permission to SCC members.  The diff inconveniently collapses to make it look like its to booth chairs.

**Comment by purelogiq** [comment]
Oh I see. No problem

**Comment by purelogiq** [comment]
Done w/ my changes

**Comment by pkoenig10** [comment]
@purelogiq changes look good.  Could you do one more small thing? Make the "Create new event type" button on the event form redirect back to the new event form like you did with tool types.  I played around with it but I'm sure you could do it much faster.

**Comment by purelogiq** [comment]
Done. I'll be gone for a while. Available at around 7:30pm

**Pull request merged**
